apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  GEMINI_API_KEY: ""
  OPENAI_API_KEY: ""
  POSTHOG_API_KEY: ""
  SENTRY_DSN: ""
  SENTRY_WEBHOOK_SECRET: ""
  RESEND_API_KEY: ""
  ARGOCD_AUTH_TOKEN: ""
