replicaCount: 1

image:
  repository: 123456789012.dkr.ecr.us-east-1.amazonaws.com/nxc-systems/nxc-nico
  pullPolicy: IfNotPresent
  tag: "latest"

dind:
  enabled: true
  image: docker:24-dind
  resources:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 1Gi

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: nico.internal.nxc.systems
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 1500m
    memory: 2Gi
  requests:
    cpu: 250m
    memory: 512Mi

nodeSelector: {}
tolerations: []
affinity: {}
