apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nxc-nico
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/nxc-systems/nxc-infrastructure.git
    targetRevision: HEAD
    path: iac/helm/nxc-nico
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: nico-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
